web:
  port: 80
  mongodb:
    serviceName: "files-service-master-mongodb"
    port: "27017"

mongodb:
  enabled: true
  replicaSet:
    enabled: false
  mongodbRootPassword: password
  mongodbDatabase: ApplicationDb
  mongodbUsername: application
  mongodbPassword: password

application:
  googlecredentials: 'Enter your credentials here'